version: '3.8'
services:

  ngx:
    image: registry.docker.loc/root/lamp:nginx
    container_name: nginx-front
    restart: always
    ports:
      - "80:80"
      - "443:443" 

  backend1:
    image: registry.docker.loc/root/lamp:back1
    container_name: back1_container
    restart: always

  backend2:
    image: registry.docker.loc/root/lamp:back2
    container_name: back2_container
    restart: always

  backend3:
    image: registry.docker.loc/root/lamp:back3
    container_name: back3_container
    restart: always

networks:
  - front:
  - backend:
